dist: xenial

services:
  - mysql

language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=trunk WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=1

before_install:
  - export PHPUNIT_DIR=/tmp/phpunit
  # Download different versions of PHPUnit depending on PHP version. WP integration tests are only compatible
  # with PHPUnit 7.x, so we can only test up to PHP 7.3 which is the maximum PHPUnit 7.x supports.
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" || ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      wget -P $PHPUNIT_DIR https://phar.phpunit.de/phpunit-5.phar && chmod +x $PHPUNIT_DIR/phpunit-5.phar;
    elif [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" || ${TRAVIS_PHP_VERSION:0:3} == "7.2" || ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then
      wget -P $PHPUNIT_DIR https://phar.phpunit.de/phpunit-7.phar && chmod +x $PHPUNIT_DIR/phpunit-7.phar;
    fi

before_script:
  - phpenv config-rm xdebug.ini
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" || ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      php $PHPUNIT_DIR/phpunit-5.phar
    elif [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" || ${TRAVIS_PHP_VERSION:0:3} == "7.2" || ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then
      php $PHPUNIT_DIR/phpunit-7.phar
    fi
